### ISSUE TITLE
Model Checkpoints have Expired

### ISSUE THREAD

**Issue by Ananya-Joshi** [jeremy-collins/sd-video-gen#2]
Hello!

Just wanted to drop a note that the model checkpoints link: https://gtvault-my.sharepoint.com/:f:/g/personal/sganesh68_gatech_edu/Esz3KxV2S5RHnlD1hizh8X4B7RuEE3CI49nyavdfzPpgTA?e=rYPomk

has expired. Are there any plans to re-upload them or can you share them by using a different platform? 

Thank you!

**Comment by jeremy-collins** [comment]
Hi Ananya, thanks for bringing this to my attention. I have uploaded the checkpoints and datasets to a different location and they should now be accessible via the new links in the README.
